apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  namespace: chrismandlv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-container
        image: ighost007/python-mysql:latest  # Using the official MySQL image from Docker Hub
        ports:
        - containerPort: 3306
