apiVersion: v1
kind: Service
metadata:
  name: kubesql-service
  namespace: chrismandlv*
spec:
  type: NodePort
  ports:
  - port: 1433*
    targetPort: 1433*
    protocol: TCP
  selector:
    app: kubesql*
