apiVersion: v1
kind: Service
metadata:
  name: sql-service
  namespace: chrismandlv
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32000
  type: NodePort
