apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: chrismandlv
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30800
  type: NodePort
